# generated by datamodel-codegen:
#   filename:  cruise_dict.json
#   timestamp: 2026-07-05T13:03:40+00:00

from __future__ import annotations

from pydantic import BaseModel


class Address(BaseModel):
    street: str
    city: str
    state: str


class AssociatedPerson(BaseModel):
    name: str
    address: Address


class FamilyMember(BaseModel):
    name: str
    address: Address


class Model(BaseModel):
    id: str
    dob: str
    paid: str
    ship_name: str
    associated_person: AssociatedPerson
    family_members: list[FamilyMember]
