# generated by datamodel-codegen:
#   filename:  cruise_dict.json
#   timestamp: 2026-07-05T13:03:40+00:00

from __future__ import annotations

from pydantic import BaseModel
import json

class Address(BaseModel):
    street: str
    city: str
    state: str


# class AssociatedPerson(BaseModel):
class PersonBio(BaseModel):
    name: str
    address: Address


# class FamilyMember(BaseModel):
#     name: str
#     address: Address


class Cruise(BaseModel):
    id: str
    dob: str
    paid: str
    ship_name: str
    associated_person: PersonBio
    family_members: list[PersonBio]

    @classmethod
    def make_cruise_from_json(cls, file_path: str) -> "Cruise":
        """ read in a json file, return a Person instance """
        with open(file_path) as file:
            return cls(**json.loads(file.read()))


cruise = Cruise.make_cruise_from_json("cruise_dict.json")
print(cruise)
print(f"{cruise.model_dump()=}")
print(f"{cruise.model_dump_json()=}")
print(f"{cruise.model_json_schema()=}")
